package hello;

import org.junit.Test;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.springframework.util.FileSystemUtils;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

public class JsonResponsePoolDatastoreTest {

    @BeforeEach
    void makeCopyOfResourcesFile(){
        File source = new File("src/test/resources/ResponsesList.json");
        new File("src/test/resources/ResponsesListCopy.json").mkdirs();
        File dest = new File("src/test/resources/ResponsesListCopy.json");
        try {
            FileSystemUtils.copyRecursively(source, dest);
        } catch (IOException e) {
        }
    }

    @AfterEach
    void deleteAutoGeneratedPath() throws IOException{
        Path path = Paths.get("src/test/resources/ResponsesListCopy.json");
        assertTrue(Files.deleteIfExists(path));
    }

    @Test
    public void loadResponsesTest() throws IOException {
        ResponsePoolDatastore responsePoolDatastore = new JsonResponsePoolDatastore("src/test/resources/ResponsesListCopy.json");
        assertEquals(3, responsePoolDatastore.getAllResponses().size());
    }

    @Test
    public void interfaceTest() throws IOException{
        ResponsePoolDatastoreTest.responsePoolDatastoreTest(new JsonResponsePoolDatastore("src/test/resources/ResponsesListCopy.json"));
    }
}
